using System.Runtime.Versioning;

namespace Mochi.Metal;

public enum MTLDataType : uint
{
    None,
    
    Struct,
    Array,
    Float,
    Float2,
    Float3,
    Float4,
    Float2x2,
    Float2x3,
    Float2x4,
    Float3x2,
    Float3x3,
    Float3x4,
    Float4x2,
    Float4x3,
    Float4x4,
    Half,
    Half2,
    Half3,
    Half4,
    Half2x2,
    Half2x3,
    Half2x4,
    Half3x2,
    Half3x3,
    Half3x4,
    Half4x2,
    Half4x3,
    Half4x4,
    Int,
    Int2,
    Int3,
    Int4,
    UInt,
    UInt2,
    UInt3,
    UInt4,
    Short,
    Short2,
    Short3,
    Short4,
    UShort,
    UShort2,
    UShort3,
    UShort4,
    Char,
    Char2,
    Char3,
    Char4,
    UChar ,
    UChar2,
    UChar3,
    UChar4,
    Bool,
    Bool2,
    Bool3,
    Bool4,
    
    [SupportedOSPlatform("macos10.13")]
    [SupportedOSPlatform("ios11.0")]
    Texture = 58,
    [SupportedOSPlatform("macos10.13")]
    [SupportedOSPlatform("ios11.0")]
    Sampler,
    [SupportedOSPlatform("macos10.13")]
    [SupportedOSPlatform("ios11.0")]
    Pointer,
    
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    R8Unorm = 62,        
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    R8Snorm,        
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    R16Unorm,       
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    R16Snorm,       
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RG8Unorm,       
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RG8Snorm,       
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RG16Unorm,      
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RG16Snorm,      
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RGBA8Unorm,     
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RGBA8Unorm_sRGB,
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RGBA8Snorm,     
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RGBA16Unorm,    
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RGBA16Snorm,    
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RGB10A2Unorm,   
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RG11B10Float,   
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios11.0")]
    [SupportedOSPlatform("tvos14.5")]
    RGB9E5Float,    
    [SupportedOSPlatform("macos10.14")]
    [SupportedOSPlatform("ios13.0")]
    RenderPipeline, 
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("maccatalyst14.0")]
    [SupportedOSPlatform("ios13.0")]
    ComputePipeline,
    [SupportedOSPlatform("macos10.14")]
    [SupportedOSPlatform("ios12.0")]
    IndirectCommandBuffer,
    [SupportedOSPlatform("macos12.0")]
    [SupportedOSPlatform("ios14.0")]
    Long, 
    [SupportedOSPlatform("macos12.0")]
    [SupportedOSPlatform("ios14.0")]
    Long2,
    [SupportedOSPlatform("macos12.0")]
    [SupportedOSPlatform("ios14.0")]
    Long3,
    [SupportedOSPlatform("macos12.0")]
    [SupportedOSPlatform("ios14.0")]
    Long4,
    
    [SupportedOSPlatform("macos12.0")]
    [SupportedOSPlatform("ios14.0")]
    ULong, 
    [SupportedOSPlatform("macos12.0")]
    [SupportedOSPlatform("ios14.0")]
    ULong2,
    [SupportedOSPlatform("macos12.0")]
    [SupportedOSPlatform("ios14.0")]
    ULong3,
    [SupportedOSPlatform("macos12.0")]
    [SupportedOSPlatform("ios14.0")]
    ULong4,
    
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("ios14.0")]
    VisibleFunctionTable = 115,
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("ios14.0")]
    IntersectionFunctionTable,
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("ios14.0")]
    PrimitiveAccelerationStructure,
    [SupportedOSPlatform("macos11.0")]
    [SupportedOSPlatform("ios14.0")]
    InstanceAccelerationStructure,
    
    [SupportedOSPlatform("macos14.0")]
    [SupportedOSPlatform("ios17.0")]
    BFloat = 121, 
    [SupportedOSPlatform("macos14.0")]
    [SupportedOSPlatform("ios17.0")]
    BFloat2,
    [SupportedOSPlatform("macos14.0")]
    [SupportedOSPlatform("ios17.0")]
    BFloat3,
    [SupportedOSPlatform("macos14.0")]
    [SupportedOSPlatform("ios17.0")]
    BFloat4,
}